import type { Achievement, FriendActivity, Game } from './types';

export const PAGE_SIZE = 6;

export const games: Game[] = [
  {
    id: 'hades-ii',
    title: 'Hades II',
    platform: 'pc',
    genre: 'Action',
    hoursPlayed: 42,
    completion: 61,
    status: 'playing',
    rating: null,
  },
  {
    id: 'astro-bot',
    title: 'Astro Bot',
    platform: 'playstation',
    genre: 'Platformer',
    hoursPlayed: 8,
    completion: 34,
    status: 'playing',
    rating: null,
  },
  {
    id: 'halo-infinite',
    title: 'Halo Infinite',
    platform: 'xbox',
    genre: 'Shooter',
    hoursPlayed: 55,
    completion: 100,
    status: 'completed',
    rating: 4,
  },
  {
    id: 'celeste',
    title: 'Celeste',
    platform: 'switch',
    genre: 'Platformer',
    hoursPlayed: 12,
    completion: 100,
    status: 'completed',
    rating: 5,
  },
  {
    id: 'bg3',
    title: "Baldur's Gate 3",
    platform: 'pc',
    genre: 'RPG',
    hoursPlayed: 0,
    completion: 0,
    status: 'backlog',
    rating: null,
  },
  {
    id: 'totk',
    title: 'The Legend of Zelda: Tears of the Kingdom',
    platform: 'switch',
    genre: 'Adventure',
    hoursPlayed: 3,
    completion: 8,
    status: 'backlog',
    rating: null,
  },
  {
    id: 'spiderman-2',
    title: "Marvel's Spider-Man 2",
    platform: 'playstation',
    genre: 'Action',
    hoursPlayed: 0,
    completion: 0,
    status: 'wishlist',
    rating: null,
  },
  {
    id: 'starfield',
    title: 'Starfield',
    platform: 'xbox',
    genre: 'RPG',
    hoursPlayed: 0,
    completion: 0,
    status: 'wishlist',
    rating: null,
  },
  {
    id: 'disco-elysium',
    title: 'Disco Elysium',
    platform: 'pc',
    genre: 'RPG',
    hoursPlayed: 31,
    completion: 100,
    status: 'completed',
    rating: 5,
  },
  {
    id: 'sea-of-stars',
    title: 'Sea of Stars',
    platform: 'switch',
    genre: 'RPG',
    hoursPlayed: 18,
    completion: 47,
    status: 'playing',
    rating: null,
  },
];

export const achievements: Achievement[] = [
  {
    id: 'hades-ii-common',
    gameId: 'hades-ii',
    title: 'First Blood',
    description: 'Defeat your first guardian at the city gates.',
    rarity: 'common',
    unlocked: true,
  },
  {
    id: 'hades-ii-rare',
    gameId: 'hades-ii',
    title: 'Night Shade',
    description: 'Clear a run using only moon-aspected keepsakes.',
    rarity: 'rare',
    unlocked: true,
  },
  {
    id: 'hades-ii-epic',
    gameId: 'hades-ii',
    title: 'Unseen Hand',
    description: 'Win a boss fight without taking a hit.',
    rarity: 'epic',
    unlocked: false,
    progress: 40,
  },
  {
    id: 'hades-ii-legendary',
    gameId: 'hades-ii',
    title: 'Speedrunner',
    description: 'Reach the surface in under twelve minutes.',
    rarity: 'legendary',
    unlocked: false,
    progress: 15,
  },
  {
    id: 'astro-bot-common',
    gameId: 'astro-bot',
    title: 'Boot Sequence',
    description: 'Rescue your first lost bot.',
    rarity: 'common',
    unlocked: true,
  },
  {
    id: 'astro-bot-rare',
    gameId: 'astro-bot',
    title: 'Pixel Perfect',
    description: 'Collect every hidden puzzle piece in a world.',
    rarity: 'rare',
    unlocked: false,
    progress: 55,
  },
  {
    id: 'astro-bot-epic',
    gameId: 'astro-bot',
    title: 'Dual Analog',
    description: 'Finish a stage using every DualSense trick once.',
    rarity: 'epic',
    unlocked: false,
    progress: 20,
  },
  {
    id: 'astro-bot-legendary',
    gameId: 'astro-bot',
    title: 'CPU of the Year',
    description: 'Rescue every bot in the galaxy.',
    rarity: 'legendary',
    unlocked: false,
    progress: 10,
  },
  {
    id: 'halo-infinite-common',
    gameId: 'halo-infinite',
    title: 'Spartan Start',
    description: 'Complete the opening mission.',
    rarity: 'common',
    unlocked: true,
  },
  {
    id: 'halo-infinite-rare',
    gameId: 'halo-infinite',
    title: 'Ring Runner',
    description: 'Clear a campaign mission on Heroic.',
    rarity: 'rare',
    unlocked: true,
  },
  {
    id: 'halo-infinite-epic',
    gameId: 'halo-infinite',
    title: 'Band of Brothers',
    description: 'Finish a co-op mission without a wipe.',
    rarity: 'epic',
    unlocked: true,
  },
  {
    id: 'halo-infinite-legendary',
    gameId: 'halo-infinite',
    title: 'LASO',
    description: 'Complete the campaign on Legendary with all skulls on.',
    rarity: 'legendary',
    unlocked: false,
    progress: 35,
  },
  {
    id: 'celeste-common',
    gameId: 'celeste',
    title: 'Forsaken City',
    description: 'Complete Chapter 1.',
    rarity: 'common',
    unlocked: true,
  },
  {
    id: 'celeste-rare',
    gameId: 'celeste',
    title: 'B-Side',
    description: 'Clear a B-Side cassette tape.',
    rarity: 'rare',
    unlocked: true,
  },
  {
    id: 'celeste-epic',
    gameId: 'celeste',
    title: 'Farewell',
    description: 'Finish the hidden ninth chapter.',
    rarity: 'epic',
    unlocked: true,
  },
  {
    id: 'celeste-legendary',
    gameId: 'celeste',
    title: 'Golden',
    description: 'Collect a golden strawberry.',
    rarity: 'legendary',
    unlocked: true,
  },
  {
    id: 'bg3-common',
    gameId: 'bg3',
    title: 'Mind Flayer',
    description: 'Survive the nautiloid crash.',
    rarity: 'common',
    unlocked: false,
    progress: 0,
  },
  {
    id: 'bg3-rare',
    gameId: 'bg3',
    title: 'Speak with Dead',
    description: 'Win a conversation you had no business winning.',
    rarity: 'rare',
    unlocked: false,
    progress: 0,
  },
  {
    id: 'bg3-epic',
    gameId: 'bg3',
    title: 'Tactician',
    description: 'Finish Act I on Tactician difficulty.',
    rarity: 'epic',
    unlocked: false,
    progress: 0,
  },
  {
    id: 'bg3-legendary',
    gameId: 'bg3',
    title: 'Absolute',
    description: 'See every origin ending in one campaign.',
    rarity: 'legendary',
    unlocked: false,
    progress: 0,
  },
  {
    id: 'totk-common',
    gameId: 'totk',
    title: 'Lookout Landing',
    description: 'Reach the surface after the tutorial sky islands.',
    rarity: 'common',
    unlocked: true,
  },
  {
    id: 'totk-rare',
    gameId: 'totk',
    title: 'Ultrahand',
    description: 'Build a vehicle that actually stays together.',
    rarity: 'rare',
    unlocked: false,
    progress: 30,
  },
  {
    id: 'totk-epic',
    gameId: 'totk',
    title: 'Sage',
    description: 'Awaken one of the regional sages.',
    rarity: 'epic',
    unlocked: false,
    progress: 0,
  },
  {
    id: 'totk-legendary',
    gameId: 'totk',
    title: 'True Founder',
    description: 'Complete every shrine on the map.',
    rarity: 'legendary',
    unlocked: false,
    progress: 4,
  },
  {
    id: 'spiderman-2-common',
    gameId: 'spiderman-2',
    title: 'Web Swing',
    description: 'Traverse a district without touching the ground.',
    rarity: 'common',
    unlocked: false,
    progress: 0,
  },
  {
    id: 'spiderman-2-rare',
    gameId: 'spiderman-2',
    title: 'Symbiote',
    description: 'Finish a combat encounter in venom form.',
    rarity: 'rare',
    unlocked: false,
    progress: 0,
  },
  {
    id: 'spiderman-2-epic',
    gameId: 'spiderman-2',
    title: 'City that Never Sleeps',
    description: '100% a borough.',
    rarity: 'epic',
    unlocked: false,
    progress: 0,
  },
  {
    id: 'spiderman-2-legendary',
    gameId: 'spiderman-2',
    title: 'Friendly Neighborhood',
    description: 'Complete every side mission as both Peters.',
    rarity: 'legendary',
    unlocked: false,
    progress: 0,
  },
  {
    id: 'starfield-common',
    gameId: 'starfield',
    title: 'One Small Step',
    description: 'Leave the mines and reach orbit.',
    rarity: 'common',
    unlocked: false,
    progress: 0,
  },
  {
    id: 'starfield-rare',
    gameId: 'starfield',
    title: 'Constellation',
    description: 'Join the explorers at the Lodge.',
    rarity: 'rare',
    unlocked: false,
    progress: 0,
  },
  {
    id: 'starfield-epic',
    gameId: 'starfield',
    title: 'Starborn',
    description: 'Complete a New Game+ jump.',
    rarity: 'epic',
    unlocked: false,
    progress: 0,
  },
  {
    id: 'starfield-legendary',
    gameId: 'starfield',
    title: 'Cartographer',
    description: 'Survey every planet in a single system.',
    rarity: 'legendary',
    unlocked: false,
    progress: 0,
  },
  {
    id: 'disco-elysium-common',
    gameId: 'disco-elysium',
    title: 'Wake Up',
    description: 'Remember your own name.',
    rarity: 'common',
    unlocked: true,
  },
  {
    id: 'disco-elysium-rare',
    gameId: 'disco-elysium',
    title: 'The Expression',
    description: 'Land a thought that changes a skill check.',
    rarity: 'rare',
    unlocked: true,
  },
  {
    id: 'disco-elysium-epic',
    gameId: 'disco-elysium',
    title: 'Moralist',
    description: 'Close the case without firing a shot.',
    rarity: 'epic',
    unlocked: true,
  },
  {
    id: 'disco-elysium-legendary',
    gameId: 'disco-elysium',
    title: 'Something Beautiful',
    description: 'Fail spectacularly, then pass the retry that matters.',
    rarity: 'legendary',
    unlocked: false,
    progress: 80,
  },
  {
    id: 'sea-of-stars-common',
    gameId: 'sea-of-stars',
    title: 'Solstice',
    description: 'Begin training as a Solstice Warrior.',
    rarity: 'common',
    unlocked: true,
  },
  {
    id: 'sea-of-stars-rare',
    gameId: 'sea-of-stars',
    title: 'Timed Hit',
    description: 'Land ten live-action timing bonuses in one fight.',
    rarity: 'rare',
    unlocked: true,
  },
  {
    id: 'sea-of-stars-epic',
    gameId: 'sea-of-stars',
    title: 'Combo Wheels',
    description: 'Fill the combo meter before the enemy acts.',
    rarity: 'epic',
    unlocked: false,
    progress: 60,
  },
  {
    id: 'sea-of-stars-legendary',
    gameId: 'sea-of-stars',
    title: 'Worlds Apart',
    description: 'Finish the true ending.',
    rarity: 'legendary',
    unlocked: false,
    progress: 25,
  },
];

export const friends: FriendActivity[] = [
  {
    id: 'maya',
    name: 'Maya Chen',
    gameTitle: 'Hades II',
    online: true,
    action: 'playing',
  },
  {
    id: 'jordan',
    name: 'Jordan Blake',
    gameTitle: 'Astro Bot',
    online: true,
    action: 'playing',
  },
  {
    id: 'sam',
    name: 'Sam Okonkwo',
    gameTitle: 'Celeste',
    online: false,
    action: 'completed',
  },
];
